#!/usr/bin/env python3
"""Generate the "Python post-processing scripts" appendix of the handout.

What it does
------------
Reads the Python scripts listed in ``SCRIPTS`` from ``code/<exercise>/`` and
embeds each one verbatim into ``document/main.tex`` as an appendix section.
Every script is wrapped in the same ``\\begin{scriptsize}\\begin{Verbatim}``
block used for the input files (``scf.in`` etc.), with a right-aligned
``--  <path>`` header line identifying the file.

The appendix is inserted just before ``\\end{document}``. The operation is
idempotent: if an appendix generated by this script is already present, it is
removed and rebuilt, so you can re-run this after editing any of the scripts
without producing duplicates.

Keep the embedded copy faithful to the tarball: the scripts must stay ASCII
(pdflatex cannot typeset bare Unicode such as Greek letters inside Verbatim)
and their lines should fit the ~16.1 cm text width in ``scriptsize`` (roughly
100 monospace characters) so they do not overflow the margin.

How to use
----------
Run from anywhere (paths are resolved relative to this file)::

    python3 gen_appendix.py

Then rebuild the handout (e.g. ``make pdf``). To add or reorder scripts, edit
the ``SCRIPTS`` list below; each entry is ``(path-under-code/, section title)``.
"""
import os

ROOT = os.path.dirname(os.path.abspath(__file__))   # repository root
TEX = os.path.join(ROOT, "document", "main.tex")
CODE = os.path.join(ROOT, "code")

# (relative path under code/, subsection heading)
SCRIPTS = [
    ("exercise2/plot.py",        r"Exercise 2: MgB$_2$ electron spectral function"),
    ("exercise3/generate_k.py",  r"Exercise 3: graphene $\mb{k}$-path generator"),
    ("exercise3/plot.py",        r"Exercise 3: graphene electron spectral function"),
    ("exercise3/plot_doped.py",  r"Exercise 3: graphene doped spectral function and self-energy"),
    ("exercise4/plot.py",        r"Exercise 4: MgB$_2$ phonon spectral function"),
]

WIDTH = 90  # right-align the filename header like scf.in


def header(path):
    pad = max(1, WIDTH - 2 - len(path))
    return "--" + " " * pad + path


def block(rel, heading):
    with open(os.path.join(CODE, rel)) as f:
        content = f.read().rstrip("\n")
    lines = []
    lines.append(r"\subsection*{" + heading + "}")
    lines.append(r"\begin{scriptsize}")
    lines.append(r" \begin{Verbatim}[frame=single]")
    lines.append(header(rel))
    lines.append(content)
    lines.append(r"\end{Verbatim}")
    lines.append(r"\end{scriptsize}")
    return "\n".join(lines)


appendix = []
appendix.append(r"\newpage")
appendix.append("")
appendix.append(r"\section*{Appendix: Python post-processing scripts}")
appendix.append("")
appendix.append(
    "For reference, we reproduce here the Python scripts used in the "
    "exercises. They are also included in the exercise directories of the "
    "tutorial tarball.")
appendix.append("")
for rel, heading in SCRIPTS:
    appendix.append(block(rel, heading))
    appendix.append("")
appendix_str = "\n".join(appendix)

with open(TEX) as f:
    tex = f.read()

marker = r"\end{document}"
appendix_header = r"\section*{Appendix: Python post-processing scripts}"

idx = tex.find(appendix_header)
if idx != -1:
    # An appendix is already present: drop it (back to the \newpage before it)
    pre = tex[:idx]
    np = pre.rfind(r"\newpage")
    body = pre[:np].rstrip("\n")
else:
    head, sep, tail = tex.rpartition(marker)
    assert sep, "could not find \\end{document}"
    body = head.rstrip("\n")

new_tex = body + "\n\n\n" + appendix_str + "\n\n" + marker + "\n"

with open(TEX, "w") as f:
    f.write(new_tex)

print("Inserted appendix with %d scripts before \\end{document}." % len(SCRIPTS))
